### ISSUE TITLE
reporting of line length in notepad is incorrect if the line is not the last line

### ISSUE THREAD

**Issue by ibrahim-s** [nvdaes/cursorLocator#5]
1.open notepad or notepad++
2. write the word hello
3. press the gesture to report line length it will say 5, correct
4. make another new line and write for instance 'world'
5. if we request the length of this new line it will be correct also
6.go back to previous line 
7. requesting the line length now it will say 7, that is incorrect.
in your script I noticed that you have checked for the existence of carriage return at the end of line, butt I noticed that in notepad and notepad++ always if the line is not last it ends with '\r\n'.
The addon is beautiful really
Thank you

**Comment by nvdaes** [comment]
Thanks for reporting, @ibrahim-s 
I'll get a look today or in the next weekend.

**Comment by nvdaes** [comment]
Hello @ibrahim-s : if you want, feel free to review PR #6. You can download the generated nvda-addon artifact for testing.
If you cannot review it, I'll merge the PR since this is fixed according to my tests.
Thanks.

**Comment by ibrahim-s** [comment]
Hello
Sorry, but I do not know why I did not receive a message for this thing
I have reviewed the pull request now and tested the addon
It has been fixed as you said and working great.
Thank you, and sorry for my unproficiency.

**Comment by nvdaes** [comment]
Oh, no worries. Thanks for reviewing and testing. I'm happy since this is fixed.
Kind regards

2021-02-06 6:33 GMT+01:00, ibrahim-s <notifications@github.com>:
