### ISSUE TITLE
Impossible to build the add-on

### ISSUE THREAD

**Issue by lukaszgo1** [nvdaes/cursorLocator#8]
### Summary

Currently add-on is not compilable due to a syntacs error in `buildVars`

### To reproduce

1. Clone the repository
2. Execute `scons` from its top directory

### Expected behavior

Add-on builds as expected.

### Relevant log output

```shell
The result of `scons` execution is:

(addons) D:\my_repos\cursorLocator>scons
scons: Reading SConscript files ...
  File "D:\my_repos\cursorLocator\buildVars.py", line 22

    "addon_version" : ,

                      ^

SyntaxError: invalid syntax

```
```


### Version

Latest master

### System configuration

_No response_

### Additional context

_No response_

**Comment by nvdaes** [comment]
Hello, I use GitHub Actions, not local environment, to run scons, so the syntax error was intentional to be fixed in the server. Anyway I fixed the error in other add-ons so they can be built by GitHub Actions and locally, so I'll use the same yaml files for this repo. My plan was to take care of the maintenance of this add-on when it can be sent to the future NVDA's store (if it's accepted), but since you opened this issue I'll try to do it in the next days.

**Comment by lukaszgo1** [comment]
Okay - I've looked into your GitHub actions and with respect the way in which you're updating the version number is unnecessarily complicated. Rather than rewriting `buildVars` and finding the right string with regex you can simply import `buildVars` in the Python code, replace the version number in the dictionary and then still from Python run `SCons.Script.Main.main()` after necessary imports. All this becomes unnecessary however if you would consider switching to the latest release of add-on template which added a handy command line option `version` which, when given to scons  overwrites whatever is in the manifest with the version provided in the CLI.

**Comment by nvdaes** [comment]
Hello, If you are sure that your suggestion is compatible with the translation system, that may use buildVars.py, please feel free to open a PR in case you think it will bring some benefits. Otherwise I"ll use Github yaml files available in other add-ons, since they work for my workflow when I merge changes in the stable branch. I don"t plan to use the latest version of add-on template since I"m not sure if it includes changes contributed by @Abdel792, who fixed at least a bug in scons for one of my add-ons. So I prefer not to use the latest changes in add-on template.

Enviado desde mi iPhone

**Comment by lukaszgo1** [comment]
> Hello, If you are sure that your suggestion is compatible with the translation system, that may use buildVars.py, please feel free to open a PR in case you think it will bring some benefits.

I'm not sure what exactly you're worried about as far as I can see scripts in the mrconfig aren't reading / writing to `buildVars` if you have specific doubts about my approach I'm happy to discuss.

>  Otherwise I"ll use Github yaml files available in other add-ons, since they work for my workflow when I merge changes in the stable branch. I don"t plan to use the latest version of add-on template since I"m not sure if it includes changes contributed by @abdel792, who fixed at least a bug in scons for one of my add-ons. So I prefer not to use the latest changes in add-on template. 

Most of changes into the sconscript that you're using are in the official add-on template already i.e. it is Python 3 only, documentation is in HTML5 and the code responsible for generating documentation attempts to translate its title (this part does not work when running in CI by the way so even if it weren't included that would not be a loss). The only part which I'm not sure about is here:
https://github.com/nvdaes/cursorLocator/blob/58e21654d99f70862d68844520948cae1cac1bd5/sconstruct#L119-L125

What exactly does that code do, why it is needed and why can't it be done in `buildVars` as opposed to sconscript. In general it is  nice to be keeping uptodate with add-on template as we can see here it avoid a lot of hassles in the long run.

**Comment by nvdaes** [comment]
Hello, I think that buildVars.py should contain the add-on version hard coded, and my idea is that, for example if there is a syntax error in buildVars, the translations system won't work. If we have the version hard-coded in buildVars.py, we can pull changes and run just scons locally, for example.
About the add-on template, I would need to compare changes and analize the code contained in my version and in the last version of the template. This would require some time. I haven't analized it, but I know that changes made by Abdel weren't included in add-on template at least when Abdel made these modifications, so simply I stopped following the evolution of the template.
You maybe right, but I would need time to see pros and cons if any.
However, I'm interested about your approach regarding buildVars. Generally we have to change the value of the add-on version writing it in buildVars. Why not to do it like me in GitHub Actions?
Cheers

**Comment by nvdaes** [comment]
BTW, the mrconfig repo has a .github/workflows/checkStableBranch.yaml, which is run when issues are created, intended to check if the stable branch of add-on is right to register an add-on in the translations system, and a step of the .yaml file contains: run scons

This workflow was sent by me, but NV Access didn't reject it and I think that run scons is performed in the server.

About the code mentioned by you, lines 119 to 125, I think this is an old code created for compatibility with Python 2 and 3.
But the fact is that the template is a dependency, I haven't followed its development, and generally is a good idea to use last versions of dependencies, but this is not always true, so I'm not sure.

**Comment by lukaszgo1** [comment]
Sorry for the delay - I was hoping @abdel792 would comment and explain their changes to the add-on template as to avoid guessing but apparently this has not happened. It seems the GitHub actions that you're using here are not kept in sync with the reference implementation described [on the wiki](https://github-wiki-see.page/m/nvdaaddons/nvdaaddons.github.io/wiki/GitHubActions) so perhaps it makes sense to open a PR against CCD repository  not here? There are essentially two things which I'd like to address:
- When creating stable release the version in `buildVars` is being updated after the tag is created in CI which makes for a pretty confusing experience (if I checkout a given tag my expectation is that it reflects the code which is released to users) and therefore in that particular case version number should be updated manually and pushed as part of the tag.
- - For the remaining actions the way in which version number is being provided is not so important as long as the add-on is build-able both on CI and on the developers systems not the case currently. I still believe using add-on template ability to provide version number is way more elegant and probably will open a PR to that effect (that would at least allow to see in the diff what has changed between your version and whatever is the latest). Since I'm curious if what I've proposed above i.e. patching version number in Python would work I'll create a second PR just to test the idea. Even if none of them gets accepted having more knowledge on GH Actions would be nice for me.

**Comment by nvdaes** [comment]
Hello, I looked at the log of addonTemplate and @Abdel792, if I"m not wrong, fixed a problem with the translation of the title of certain add-ons. This seems to be implemented in the addonTemplate. When I start my computer I"ll see your PR in clipContentsDesigner and probably I"ll merge it. If any issue is detected later, we can try to fix it.
I"m also thinking to make an experimental change to include an extra asset in releases with the future metadata (json file) required according to the planned addon-store-submission in the current state. But I"m thinking if this will be or not useful. I"ll see all this. Thanks.

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
I probably try to use the workflow dispatch event to build the tag in the server, along with changes in buildVars.py, and then push buildVars and the tag. Really changing buildVars locally is not a problem, but I think it maybe avoided. I"ll see, just thinking now.



Enviado desde mi iPhone
